name: Update Character Avatar

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    character:
      description: 'Код персонажа'
      default: amber
      required: true
      type: string

    avatar_url:
      description: 'Адрес аватарки вроде https://genshin.honeyhunterworld.com/img/char/amber_face.png, только квадратная и центрированная'
      required: true
      type: string

    portrait_url:
      description: 'Адрес портрета вроде https://genshin-impact.fandom.com/wiki/Amber?file=Character+Amber+Portrait.png (но нужно проверить качество, а то они любят заливать пнг с 256 цветами)'
      required: true
      type: string

    branch:
      description: 'Ветка'
      default: master
      required: true
      type: string

jobs:
  build:
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.11.1

      - run: wget "${{ inputs.avatar_url }}" -O /tmp/avatar.png

      - run: wget "${{ inputs.portrait_url }}" -O /tmp/portrait.png

      - run: npm install
        working-directory: ${{ env.GITHUB_WORKSPACE }}

      - run: ./scripts/prepare.js avatar --code amber --src /tmp/avatar.png
        working-directory: ${{ env.GITHUB_WORKSPACE }}

      - run: ./scripts/prepare.js portrait --code amber --src /tmp/portrait.png
        working-directory: ${{ env.GITHUB_WORKSPACE }}

      - name: Git user info
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"

      - name: Pushing build
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: |
          git checkout ${{ inputs.branch }}
          git add www/public/media
          git commit -m "New ${{ inputs.character }} images"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git ${{ inputs.branch }}
